apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-server-conf
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    # No need to scrape otel collector, metrics will be pushed via remote_write
    # scrape_configs:
    #   - job_name: 'prometheus'
    #     static_configs:
    #       - targets: ['localhost:9090']
    storage:
      tsdb:
        out_of_order_time_window: 10m
    remote_write:
      - url: http://prometheus.observability.svc.cluster.local:9090/api/v1/write
