apiVersion: tesselar.io/v1alpha1
kind: xAuthClient
metadata:
  name: openwebui6
  namespace: openwebui
spec:
  applicationName: openwebui6
  redirectUris:
    - "https://openwebui.example.com/oauth/callback"
  postLogoutRedirectUris:
    - "https://openwebui.example.com"
