apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui
  annotations: {}
spec:
  rules:
    - host: openwebui.${DOMAIN}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openwebui
                port:
                  name: web
