{
 "title": "App",
 "description": "Monitors App's metrics and logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(k8s_node_cpu_time_seconds_total, k8s_node_name)"
    }
   },
   {
    "name": "app",
    "label": "App",
    "query": {
     "query": "label_values(container_cpu_usage,k8s_namespace_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "App usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$used / ($available + $used) ", "type": "math" }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m " } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_cpu_time_seconds_total{k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_available_bytes{k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}) + sum(k8s_pod_memory_working_set_bytes{k8s_node_name=~\"^$Node$\",  k8s_namespace_name=~\"^$app$\"})"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_namespace_name=\"podinfo\"}"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Node Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_io_bytes_total{direction=\"receive\", k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}[1m])) ",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(k8s_pod_network_io_bytes_total{direction=\"transmit\", k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_cpu_time_seconds_total{k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}[1m])) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Containers CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_time_seconds_total{k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}[1m])) by (k8s_container_name, k8s_pod_name)",
     "legendFormat": "pod: {{ k8s_pod_name }} | {{ k8s_container_name }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Containers memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}) by (k8s_container_name, k8s_pod_name)",
     "legendFormat": "pod: {{ k8s_pod_name }} | {{ k8s_container_name }}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_io_bytes_total{direction=\"receive\", k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}[1m])) by (k8s_pod_name)",
     "legendFormat": "-> {{k8s_pod_name}}"
    },
    {
     "expr": "- sum(rate(k8s_pod_network_io_bytes_total{direction=\"transmit\", k8s_node_name=~\"^$Node$\", k8s_namespace_name=~\"^$app$\"}[1m])) by (k8s_pod_name)",
     "legendFormat": "<- {{k8s_pod_name}}"
    }
   ]
  }
 ]
}