{
 "title": "Cluster",
 "description": "Monitors Kubernetes cluster using OpenTelemetry kubeletstats metrics. Shows overall cluster CPU / Memory / Filesystem usage as well as individual pod and container statistics.",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": {
     "query": "label_values(k8s_node_cpu_time_seconds_total, k8s_node_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Total Node Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster memory usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$used / ($available + $used) ", "type": "math" }
   ]
  },
  {
   "title": "Cluster CPU usage (cores, 1m avg)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k8s_node_cpu_time_seconds_total{k8s_node_name=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cluster filesystem usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_node_filesystem_usage_bytes{k8s_node_name=~\"^$Node$\"}) / sum(k8s_node_filesystem_capacity_bytes{k8s_node_name=~\"^$Node$\"}) * 100"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_node_memory_working_set_bytes{k8s_node_name=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_node_memory_available_bytes{k8s_node_name=~\"^$Node$\"}) + sum(k8s_node_memory_working_set_bytes{k8s_node_name=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(k8s_node_cpu_time_seconds_total{k8s_node_name=~\"^$Node$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_node_filesystem_usage_bytes{k8s_node_name=~\"^$Node$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(k8s_node_filesystem_capacity_bytes{k8s_node_name=~\"^$Node$\"})"
    }
   ]
  },
  { "title": "Network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Node Network I/O",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_io_bytes_total{direction=\"receive\", k8s_node_name=~\"^$Node$\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "-sum(rate(k8s_pod_network_io_bytes_total{direction=\"transmit\", k8s_node_name=~\"^$Node$\"}[1m]))",
     "legendFormat": "Sent"
    }
   ]
  },
  { "title": "Node filesystem usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(k8s_node_filesystem_usage_bytes{k8s_node_name=~\"^$Node$\"}) by (k8s_node_name)",
     "legendFormat": "{{k8s_node_name}}"
    }
   ]
  },
  { "title": "Pods CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Pods CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_cpu_time_seconds_total{k8s_node_name=~\"^$Node$\"}[1m])) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Containers CPU usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Containers CPU usage (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "cores" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_time_seconds_total{k8s_node_name=~\"^$Node$\"}[1m])) by (k8s_container_name, k8s_pod_name)",
     "legendFormat": "pod: {{ k8s_pod_name }} | {{ k8s_container_name }}"
    }
   ]
  },
  { "title": "Pods memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Pods memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(k8s_pod_memory_working_set_bytes{k8s_node_name=~\"^$Node$\"}) by (k8s_pod_name)",
     "legendFormat": "{{k8s_pod_name}}"
    }
   ]
  },
  { "title": "Containers memory usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Containers memory usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{k8s_node_name=~\"^$Node$\"}) by (k8s_container_name, k8s_pod_name)",
     "legendFormat": "pod: {{ k8s_pod_name }} | {{ k8s_container_name }}"
    }
   ]
  },
  { "title": "Pods network I/O", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Pods network I/O (1m avg)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(k8s_pod_network_io_bytes_total{direction=\"receive\", k8s_node_name=~\"^$Node$\"}[1m])) by (k8s_pod_name)",
     "legendFormat": "-> {{k8s_pod_name}}"
    },
    {
     "expr": "- sum(rate(k8s_pod_network_io_bytes_total{direction=\"transmit\", k8s_node_name=~\"^$Node$\"}[1m])) by (k8s_pod_name)",
     "legendFormat": "<- {{k8s_pod_name}}"
    }
   ]
  }
 ]
}