apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-credentials
  namespace: kube-system
  annotations:
    fluxcd.io/ignore: "true"
type: Opaque
stringData:
  CLOUDFLARE_EMAIL: "placeholder"
  CLOUDFLARE_API_KEY: "placeholder"
