apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-coredns-conf
  namespace: kube-system
data:
  Corefile: |
    # BLOCK 1: Handle your custom domain home.mauriciomelo.io
    home.mauriciomelo.io:53 {
        log
        errors
        # This creates a CNAME for any *.home.mauriciomelo.io query,
        # pointing it to your pod's stable Tailscale MagicDNS name.
        hosts {
          tesselar-proxy.tail15a315.ts.net   *.home.mauriciomelo.io
        }
    }
