apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-coredns-conf
  namespace: kube-system
data:
  Corefile: |
    home.mauriciomelo.io:53 {
      log
      errors

      template IN A *.home.mauriciomelo.io {
          answer "{{ .Name }} 60 IN A 100.110.184.68"
      }

      template IN A home.mauriciomelo.io {
          answer "{{ .Name }} 60 IN A 100.110.184.68"
      }
    }
