apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-coredns-conf
  namespace: kube-system
data:
  Corefile: |
    home.mauriciomelo.io:53 {
        log
        errors

        # Always return a CNAME record for any query under home.mauriciomelo.io
        template IN CNAME . {
            match ^(.*)\.home\.mauriciomelo\.io\.$
            answer "{{ .Name }} 60 IN CNAME tesselar-proxy.tail15a315.ts.net."
        }

        # Do not forward/resolve tesselar-proxy.tail15a315.ts.net itself
        # Just return NXDOMAIN if someone queries it here
        template IN A tesselar-proxy.tail15a315.ts.net {
            rcode NXDOMAIN
        }
        template IN AAAA tesselar-proxy.tail15a315.ts.net {
            rcode NXDOMAIN
        }
    }
