apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-serve-config
  namespace: kube-system
data:
  serve.json: |
    {
      "TCP": {
        "443": {
          "HTTPS": true,
          "Proxy": "http://127.0.0.1:8443"
        }
      }
    }
