services:
  tailscale:
    container_name: tailscale
    hostname: homelab-tailscale
    image: tailscale/tailscale:stable
    volumes:
      - ${SERVICE_DATA}/tailscale:/var/lib # State data will be stored in this directory
      - /dev/net/tun:/dev/net/tun # Required for tailscale to work
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
    cap_add: # Required for tailscale to work
      - net_admin
      - sys_module
    command: tailscaled
    privileged: true
    restart: always
