apiVersion: v1
kind: LimitRange
metadata:
  name: observability-resource-limits
  namespace: observability
spec:
  limits:
    - type: Container
      max:
        ephemeral-storage: "4Gi"
      default:
        ephemeral-storage: "4Gi"
