apiVersion: v1
kind: LimitRange
metadata:
  name: observability-resource-limits
  namespace: observability
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: "1Gi"
        ephemeral-storage: "1Gi"
      default:
        memory: "1Gi"
        ephemeral-storage: "1Gi"
