apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
configMapGenerator:
  - name: grafana-dashboards
    files:
      - dashboards/cluster.json
      - dashboards/app.json
  - name: grafana-dashboard-provider
    files:
      - dashboard-provider.yaml
generatorOptions:
  disableNameSuffixHash: true
resources:
  - grafana.yaml
  - ingress.yaml
