apiVersion: tesselar.io/v1alpha1
kind: App
metadata:
  name: syncthing
spec:
  image: syncthing/syncthing:v2.0.16
  ports:
    - name: gui
      containerPort: 8384
    - name: sync-tcp
      containerPort: 22000
    - name: discovery
      containerPort: 21027
  envVariables:
    - name: PUID
      value: "1000"
    - name: PGID
      value: "1000"
    - name: STGUIADDRESS
      value: 0.0.0.0:8384
  volumeMounts:
    - mountPath: /var/syncthing
      name: data
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
  ingress:
    port:
      name: gui
  health:
    check:
      type: httpGet
      path: /rest/noauth/health
      port: gui
  overrides:
    deploymentJsonPatches:
      - op: add
        path: /spec/template/spec/securityContext
        value:
          fsGroup: 1000
      - op: add
        path: /spec/template/spec/hostNetwork
        value: true
      - op: add
        path: /spec/template/spec/dnsPolicy
        value: ClusterFirstWithHostNet
      - op: add
        path: /spec/template/spec/volumes
        value:
          - name: sync-data
            nfs:
              server: truenas.lan
              path: /mnt/store/home-cluster/syncthing
      - op: add
        path: /spec/template/spec/containers/0/volumeMounts
        value:
          - name: data
            mountPath: /var/syncthing
          - name: sync-data
            mountPath: /sync
