apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: zitadel-tf-composition
spec:
  compositeTypeRef:
    apiVersion: tesselar.io/v1alpha1
    kind: xAuthClient
  mode: Pipeline
  pipeline:
    - step: patch-and-transform
      functionRef:
        name: crossplane-contrib-function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: PatchAndTransform
        resources:
          - name: zitadel-oidc-app
            base:
              apiVersion: opentofu.m.upbound.io/v1beta1
              kind: Workspace
              metadata:
                name: placeholder-name
                namespace: crossplane-system
              spec:
                providerConfigRef:
                  name: zitadel-tf-provider-config
                  kind: ClusterProviderConfig
                forProvider:
                  varmap:
                    application_name: ""
                    redirect_uris: ""
                    post_logout_redirect_uris: ""
                  source: Inline
                  module: |
                    variable "application_name" {
                      type = string
                    }
                    variable "redirect_uris" {
                      type = list(string)
                    }
                    variable "post_logout_redirect_uris" {
                      type = list(string)
                    }

                    locals {
                      org_name     = "tesselar_org"
                      project_name = "tessellar_apps"
                      org_exists = length(data.zitadel_orgs.by_name.ids) > 0
                      project_exists = local.org_exists ? length(data.zitadel_projects.by_name[0].project_ids) > 0 : false
                    }

                    data "zitadel_orgs" "by_name" {
                      name        = local.org_name
                      name_method = "TEXT_QUERY_METHOD_EQUALS"
                    }

                    resource "zitadel_org" "default" {
                      count = local.org_exists ? 0 : 1
                      name  = local.org_name
                    }

                    locals {
                      org_id = coalesce(try(zitadel_org.default[0].id, null), try(data.zitadel_orgs.by_name.ids[0], null))
                    }

                    data "zitadel_projects" "by_name" {
                      count = local.org_exists ? 1 : 0
                      org_id      = data.zitadel_orgs.by_name.ids[0]
                      name        = local.project_name
                      name_method = "TEXT_QUERY_METHOD_EQUALS"
                    }

                    resource "zitadel_project" "default" {
                      count = local.project_exists ? 0 : 1
                      name                     = local.project_name
                      org_id                   = local.org_id 
                      project_role_assertion   = true
                      project_role_check       = true
                      has_project_check        = true
                      private_labeling_setting = "PRIVATE_LABELING_SETTING_ENFORCE_PROJECT_RESOURCE_OWNER_POLICY"
                    }

                    locals {
                      project_id = coalesce(
                        try(zitadel_project.default[0].id, null), 
                        try(data.zitadel_projects.by_name[0].project_ids[0], null)
                      )
                    }

                    resource "zitadel_application_oidc" "default" {
                      org_id                      = local.org_id
                      project_id                  = local.project_id
                      name                        = var.application_name
                      redirect_uris               = var.redirect_uris
                      post_logout_redirect_uris   = var.post_logout_redirect_uris
                      response_types              = ["OIDC_RESPONSE_TYPE_CODE"]
                      grant_types                 = ["OIDC_GRANT_TYPE_AUTHORIZATION_CODE"]
                    }

                    output "client_secret" {
                      value       = zitadel_application_oidc.default.client_secret
                      sensitive   = true
                    }

                    output "client_id" {
                      value       = zitadel_application_oidc.default.client_id
                      sensitive   = true
                    }
            patches:
              - fromFieldPath: "metadata.name"
                toFieldPath: "metadata.name"
              - fromFieldPath: "metadata.namespace"
                toFieldPath: "metadata.namespace"
              - fromFieldPath: "metadata.namespace"
                toFieldPath: "spec.writeConnectionSecretToRef.namespace"
              - fromFieldPath: "metadata.name"
                toFieldPath: "spec.writeConnectionSecretToRef.name"
              - fromFieldPath: "spec.applicationName"
                toFieldPath: "spec.forProvider.varmap.application_name"
              - fromFieldPath: "spec.redirectUris"
                toFieldPath: "spec.forProvider.varmap.redirect_uris"
              - fromFieldPath: "spec.postLogoutRedirectUris"
                toFieldPath: "spec.forProvider.varmap.post_logout_redirect_uris"
