apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: observability
  values:
    image:
      repository: otel/opentelemetry-collector-contrib
    mode: daemonset
    presets:
      logsCollection:
        enabled: true
      kubernetesAttributes:
        enabled: true
      kubeletMetrics:
        enabled: true
      hostMetrics:
        enabled: true
    config:
      exporters:
        otlphttp:
          endpoint: "http://loki.observability.svc.cluster.local:3100/otlp"
        prometheusremotewrite:
          endpoint: "http://prometheus.observability.svc.cluster.local:9090/api/v1/write"
          tls:
            insecure: true
          resource_to_telemetry_conversion:
            enabled: true
      service:
        pipelines:
          logs:
            exporters:
              - otlphttp
            processors:
              - memory_limiter
              - batch
            receivers:
              - otlp
          metrics:
            exporters: [prometheusremotewrite]
    ports:
      prometheus:
        enabled: false
        containerPort: 8889
        servicePort: 8889
        hostPort: 8889
        protocol: TCP
    service:
      enabled: true
      type: ClusterIP
