apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opentelemetry-collector
  namespace: observability
spec:
  interval: 5m
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: open-telemetry
        namespace: observability
  values:
    image:
      repository: otel/opentelemetry-collector-contrib
    mode: daemonset
    presets:
      logsCollection:
        enabled: true
      kubernetesAttributes:
        enabled: true
    config:
      exporters:
        otlphttp:
          endpoint: "http://loki.observability.svc.cluster.local:3100/otlp"
      service:
        pipelines:
          logs:
            exporters:
              - otlphttp
            processors:
              - memory_limiter
              - batch
            receivers:
              - otlp
