apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: podinfo
namespace: podinfo
resources:
  - hpa.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - namespace.yaml
