apiVersion: v1
kind: ConfigMap
metadata:
  name: tailscale-proxy-serve-config
  namespace: kube-system
data:
  serve.json: |
    {
      "TCP": {
        "80": {
          "TCPForward": "127.0.0.1:8000"
        },
        "443": {
          "TCPForward": "127.0.0.1:8443"
        }
      }
    }
